.TH "src Directory Reference" 3 "Wed Apr 26 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBatiendecliente\&.c\fP"
.br
.ti -1c
.RI "file \fBirccommands\&.c\fP"
.br
.ti -1c
.RI "file \fBircserver\&.c\fP"
.br
.RI "\fIFunciones de manejo de variables globales\&. \fP"
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "\fIServidor IRC v0\&.0\&. \fP"
.ti -1c
.RI "file \fButilities\&.c\fP"
.br
.in -1c
