.TH "srclib Directory Reference" 3 "Fri May 5 2017" "Redes 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srclib Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdaemonizer\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2302-05-P1-atiendecliente\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2302-05-P1-irccommands\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2302-05-P1-ircserver\&.c\fP"
.br
.RI "\fIFunciones de manejo de variables globales\&. \fP"
.ti -1c
.RI "file \fBG-2302-05-P1-utilities\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2302-05-P2-rcommands\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2302-05-P2-tcp_tools\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2302-05-P2-ucommands\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2302-05-P2-udp_tools\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2302-05-P3-ssl_server\&.c\fP"
.br
.RI "\fILibrería de manejo de un servidor de sockets SSL\&. \fP"
.ti -1c
.RI "file \fBG-2302-05-P3-ssl_tools\&.c\fP"
.br
.RI "\fILibrería de manejo de la capa SSL\&. \fP"
.in -1c
