.TH "src Directory Reference" 3 "Wed May 3 2017" "Redes 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBG-2302-05-P1-atiendecliente\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2302-05-P1-irccommands\&.c\fP"
.br
.ti -1c
.RI "file \fBG-2302-05-P1-ircserver\&.c\fP"
.br
.RI "\fIFunciones de manejo de variables globales\&. \fP"
.ti -1c
.RI "file \fBG-2302-05-P1-main\&.c\fP"
.br
.RI "\fIServidor IRC v0\&.0\&. \fP"
.ti -1c
.RI "file \fBG-2302-05-P1-utilities\&.c\fP"
.br
.in -1c
