.TH "includes/G-2302-05-P1-main.h" 3 "Wed May 3 2017" "Redes 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/G-2302-05-P1-main.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include 'G-2302-05-P1-ircserver\&.h'\fP
.br
\fC#include 'G-2302-05-P1-atiendecliente\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_QUEUE\fP   10"
.br
.ti -1c
.RI "#define \fBDEFAULT_PORT\fP   6667"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "AUTHOR"
.PP
Maria Prieto Gil maria.prietogil@estudiante.uam.es 
.SH "AUTHOR"
.PP
David Nevado Catalan david.nevadoc@estudiante.uam.es 
.SH "DATE"
.PP
02/05/2017 
.SH "Author"
.PP 
Generated automatically by Doxygen for Redes 2 from the source code\&.
