.TH "src/main.c" 3 "Wed Apr 26 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- 
.PP
Servidor IRC v0\&.0\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./includes/main\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmanejador_SIGINT\fP (int sig)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "\fIMain del servidor\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBstop\fP =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Servidor IRC v0\&.0\&. 

Version 0 del sevidor IRC
.SH "AUTHOR"
.PP
Maria Prieto 
.SH "AUTHOR"
.PP
David Nevado Catalan
.SH "DATE"
.PP
12/02/2017 
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Main del servidor\&. Funcion Main del servidor\&. Gestiona los parametros pasados por el usuario y abre un socket para ponerse a la espera de mensajes en el puerto deseado\&. 
.SH "RETURN"
.PP
ERROR si se produce un fallo que provoca una salida inseperada OK salida controlada con el cierre del servidor 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
