.TH "taudio_data" 3 "Fri May 5 2017" "Redes 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
taudio_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBip\fP"
.br
.ti -1c
.RI "long \fBport\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Redes 2 from the source code\&.
